### ISSUE TITLE
Vanilla 1.4.4.9 release built from the wrong commit

### ISSUE THREAD

**Issue by Danrs4114** [ryansheehan/terraria#149]
Hi

The Vanilla 1.4.4.9 release on [GitHub](https://github.com/ryansheehan/terraria/releases/tag/vanilla-1.4.4.9) and Docker Hub unfortunately seems to have been built from [the wrong commit](https://github.com/ryansheehan/terraria/commit/54a0f3bf8e19eeb2664e2a4e5cc86c91df87d880) (Terraria Mobile).
It should probably have been based on [this pull request](https://github.com/ryansheehan/terraria/pull/148). 🙂

**Comment by ryansheehan** [comment]
I messed up the release, deleted the current one and rebuilding it now

**Comment by Danrs4114** [comment]
Perfect. Thank you.
Kudos to you for the quick response, and in general for being quick to merge pull requests and build new releases 😀
