### ISSUE TITLE
Very large log files being produced

### ISSUE THREAD

**Issue by breadcat** [ryansheehan/terraria#19]
I've come across this issue on two separate servers using this image, it seems that if the container is just allowed to run on its own for long periods of time it will produce log files in the gigabytes range.

```
[root@atlas 53d28fc2690f8914d10003a63ca801c18c434f501d07b0e4a5bb2e15486d73af]# pwd
/var/lib/docker/containers/53d28fc2690f8914d10003a63ca801c18c434f501d07b0e4a5bb2e15486d73af
[root@atlas 53d28fc2690f8914d10003a63ca801c18c434f501d07b0e4a5bb2e15486d73af]# ls -lah
total 481G
drwx------  4 root root 4.0K Dec 19 18:41 .
drwx------ 46 root root  12K Jan 15 12:09 ..
-rw-r-----  1 root root 481G Dec 19 18:40 53d28fc2690f8914d10003a63ca801c18c434f501d07b0e4a5bb2e15486d73af-json.log
drwx------  2 root root 4.0K Dec  4 23:19 checkpoints
-rw-------  1 root root 3.9K Dec 19 18:41 config.v2.json
-rw-r--r--  1 root root 1.3K Dec 19 18:41 hostconfig.json
-rw-r--r--  1 root root   13 Dec  4 23:20 hostname
-rw-r--r--  1 root root  175 Dec  4 23:20 hosts
-rw-r--r--  1 root root   62 Dec  4 23:20 resolv.conf
-rw-r--r--  1 root root   71 Dec  4 23:20 resolv.conf.hash
drwx------  2 root root 4.0K Dec  4 23:20 shm
[root@atlas 53d28fc2690f8914d10003a63ca801c18c434f501d07b0e4a5bb2e15486d73af]#
```

I can't upload this log file in it's entirety, but I can give snippets from it if you'd like me to.

**Comment by ryansheehan** [comment]
googling around for the issue, it looks like you can add a `--log-opt max-size=50m ` to your run command; as long as the docker version installed is greater than 1.8.  Another potential option is to disable logging all together with `--log-driver none`.

This would be good info for the README if it works.  I'm not sure if I'll have much time to poke around this issue any time soon.  If you have a chance, see if either of these work let me know.

**Comment by breadcat** [comment]
You're right with this, I've added 
```
    logging:
      options:
        max-size: 200k
```

to my docker-compose file and now this log is kept in check. Thanks for your help with this.
