### ISSUE TITLE
I cant connect to the server

### ISSUE THREAD

**Issue by icehaku** [ryansheehan/terraria#20]
My world is running by I can't connect to it via game.

**Comment by ryansheehan** [comment]
It might mean the server is out of date with the client.  Probably need to
update the version of  tshock.  I'll look into it asap.

**Comment by icehaku** [comment]
I fixed, my problem was the "Security Group" configuration, I needed to open the inbound connections:
![image](https://user-images.githubusercontent.com/3009342/40881363-e3d61f40-669a-11e8-9134-a6dbefac9311.png)
I know this could be more secure, but that worked.
