### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by JackTGarland** [ryansheehan/terraria#29]
I have been playing around trying to get the docker to run and am currently looking inside the docker and am getting this error.

"System.NullReferenceException: Object reference not set to an instance of an object
  at Terraria.Main.DedServ () [0x009b8] in <b4e241b9661d4116aa0e14001e189f09>:0
  at Terraria.Program.LaunchGame (System.String[] args, System.Boolean monoArgs) [0x00092] in <b4e241b9661d4116aa0e14001e189f09>:0"

It is about terrira but no amount of googling shows me where the error is from.

If you can shed some light or let me know how I can find the cause of it that would be great as ServerLog.txt dose not exist.

**Comment by ryansheehan** [comment]
This looks to be crashing, not in docker, but, in tshock itself.   I wonder
if you're running into version incompatibility?

tshock team has not released their update to support Terraria v1.4 yet.  As
soon as I see a release I'll update the docker container.

**Comment by ryansheehan** [comment]
pre-release of v1.4 container is up.  Not sure if plugins will work, but i
was able to connect.

**Comment by JackTGarland** [comment]
Interesting. I just loaded it up as a fresh container and I am still getting that error. T shock 4.3.26.0?
I will see what happens if I generate a new world.

**Comment by JackTGarland** [comment]
I just noticed that when creating a world it says the server is running 1.3.5.3.
![image](https://user-images.githubusercontent.com/34702783/82242001-038b5200-9935-11ea-9d04-b1b6ad9b5197.png)

**Comment by JackTGarland** [comment]
So I was trying to use a world from 1.4 that was causing the issue. Creating a new world worked fine.
