### ISSUE TITLE
The image 1.4.0.2-pre1 does not load tshock

### ISSUE THREAD

**Issue by fallobst22** [ryansheehan/terraria#30]
From the [release notes of Tshock 4.4.0 pre1](https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre1):

> Important: You need to move TShockAPI.dll into the ServerPlugins folder. If you don't have one, run TerrariaServer.exe once, and then copy the file into the newly created folder. You know that you're running TShock as expected if you see the list of names in the startup sequence.

Currently the docker image does not copy the file into the ServerPlugins folder. Therefore tshock is not loaded.

**Comment by ryansheehan** [comment]
I republished the tag with a bootstrap file to do the copy of the TShockAPI.dll
