### ISSUE TITLE
please update to Tshok 4.4.0-pre2

### ISSUE THREAD

**Issue by NoeelMoeskops** [ryansheehan/terraria#32]
This update is not even an hour old. And I saw that you just updated to pre1. But there is a newer version available: https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre2

**Comment by ryansheehan** [comment]
Things are updating faster than i can type!  Just pushed an update.

**Comment by ryansheehan** [comment]
ugh, just found an issue, things were packaged differently and no longer require the TShockAPI.dll to be copied...

**Comment by NoeelMoeskops** [comment]
Thank you!
