### ISSUE TITLE
TShock Worldselect on every startup and authcode

### ISSUE THREAD

**Issue by Chaoschaot232** [ryansheehan/terraria#35]
Hey,

I created a new world and loaded it directly into this docker image but on every start of the container, I must attach to it, choose the world where to play on (uploaded world gets recognized) and must also tell every time how many maxplayer, ports, port forwarding and so on ...

Normaly, while providing the world by "-world=/world/world.wld" it should normaly load that world instantly, shouldn't it? And after doing the stuff above for the first time, it should save my choises but it doens't do it.

So either smth. within TShock goes wrong or a few additional environments are missed out here.
Could this be reviewed please?

Cheers
Marcel

**Comment by ryansheehan** [comment]
I havent been able to reproduce this locally.  Did you use the container to build your world?

**Comment by JackTGarland** [comment]
Could this be linked to the change in world path from tshock?

**Comment by ryansheehan** [comment]
This is, I updated the docs to reflect that change.
