### ISSUE TITLE
Terraria cut a new release: 1.4.0.3

### ISSUE THREAD

**Issue by mattlorimor** [ryansheehan/terraria#37]
Not sure if there is a new tshock release for it, yet.

**Comment by kevinle-1** [comment]
No new TShock release yet but known issue and the devs working on an update. Should be soon.

**Comment by TodaysSawyer** [comment]
New TShock release live:
https://github.com/Pryaxis/TShock/releases/tag/v4.4.0-pre5

**Comment by ryansheehan** [comment]
TShock now released a pre6 and completely took down pre5...  I published an update.
