### ISSUE TITLE
Issue with most of GUI docker apps when trying to use existing world

### ISSUE THREAD

**Issue by akanistudio** [ryansheehan/terraria#39]
According to bootstrap.sh file and documentation I can add any variables for TerrariaServer.exe after docker run command:
```
#!/bin/sh

echo "\nBootstrap:\nconfigpath=$CONFIGPATH\nworldpath=$WORLDPATH\nlogpath=$LOGPATH\n"
echo "Copying plugins..."
cp -Rfv /plugins/* ./ServerPlugins

mono --server --gc=sgen -O=all TerrariaServer.exe -configPath "$CONFIGPATH" -worldpath "$WORLDPATH" -logpath "$LOGPATH" "$@" 
```

However my GUI docker hosting does not allow me to set custom commands, I can only add environment variables like $CONFIGPATH, $WORLDPATH, $LOGPATH. 

Could you please add $WORLD variable with the name of the world as well? Like:
`mono --server --gc=sgen -O=all TerrariaServer.exe -configPath "$CONFIGPATH" -worldpath "$WORLDPATH" -logpath "$LOGPATH" -world "$WORLD" "$@"`

That would fix my issue.

**Comment by cxbeat** [comment]
I agree with this. I guess you can fork it, modify it, and then make a pull request.

**Comment by akanistudio** [comment]
Eventually config file path in env variables would do as well.

**Comment by akanistudio** [comment]
Aight, I created pull request for it, but the only test I did was checking on steam version of game if
`TerrariaServer.exe -world "" ` works, and seems like leaving variable empty will work fine if someone dont wanna load world but create new one.

**Comment by ryansheehan** [comment]
I added WORLD_FILENAME environment variable that can be used in place of the -world flag in the latest release.  Forewarning though, TShock removed the -worldpath flag so the volume mount has changed from /world to /root/.local/share/Terraria/Worlds

The WORLD_FILENAME is just the file name of the world inside the mounted directory.
