### ISSUE TITLE
Docker CI build error

### ISSUE THREAD

**Issue by Accendit** [ryansheehan/terraria#45]
Hi,

First of all I'd like to thank you for updating this image so quickly, great work!

However it seems like there's something going wrong in the DockerCI builds. I'd help but it seems like I can't access its logs (set to private?)

**Comment by blaas** [comment]
It is most likely related to the faulty zip file name error that should be solved by this PR : https://github.com/ryansheehan/terraria/pull/44

**Comment by RageBoy009** [comment]
why is the docker container not build automatically as soon as the github gets updates?

**Comment by ryansheehan** [comment]
Those are from a temporary setup.  For a while I was exploring building
from source, and looking to contribute the dockerfile back to tshock.

For a number of reasons I had to switch back to building from the release
zips.  I still hope to reactivate that effort of building from source.  But
I'm going to wait until the pre release phase is over.

**Comment by Accendit** [comment]
@ryansheehan That's a great idea! Tshock having an official image would be awesome.

I think using a development or feature branch might provide a more ideal workflow for working on that though 🙂

Thanks for solving this so quickly and creating this image!
