### ISSUE TITLE
Enabling Journey?

### ISSUE THREAD

**Issue by Clete2** [ryansheehan/terraria#47]
I need a bit of help. I'm brand new to Terraria. I want to make a journey server but it doesn't seem to be working. Can someone point me to what I'm doing wrong?

I am trying to set it to Journey mode by setting `-difficulty 3` but it is not working. When I try to join it tells me that a journey character cannot join a non-journey server.

`docker run -it -p 7777:7777 --rm -v /var/lib/docker/volumes/terraria_terraria/_data/:/root/.local/share/Terraria/Worlds ryshe/terraria:latest -world /root/.local/share/Terraria/Worlds/Universe.wld -autocreate 3 -difficulty 3`

Server config reference (search difficulty on page): https://terraria.gamepedia.com/Server

**Comment by ryansheehan** [comment]
I would do a first run for world generation

docker run -it -p 7777:7777 --rm -v
> /var/lib/docker/volumes/terraria_terraria/_data:/root/.local/share/Terraria/Worlds
> ryshe/terraria:latest


this will walk you through the world generation.  Then on subsequent runs
use the -world flag for loading the save file you generated, and the -d
flag for docker to run it in the background

>
> docker run -d -p 7777:7777 --rm
> -v /var/lib/docker/volumes/terraria_terraria/_data:/root/.local/share/Terraria/Worlds
> ryshe/terraria:latest -world /root/.local/share/Terraria/
> Worlds/Universe.wld

**Comment by Clete2** [comment]
Nice. I’ll try that after work and get back to you. Appreciate your quick reply.

**Comment by Clete2** [comment]
Oh wow turns out difficulty=4 is what it should've been.

Your command worked swimmingly. Thanks again @ryansheehan !
