### ISSUE TITLE
Is it possible to upgrade to pre12 by running the update command?

### ISSUE THREAD

**Issue by tutivog** [ryansheehan/terraria#52]

**Comment by ryansheehan** [comment]
I'm not sure I fully understand your question.  Right now the `:latest` tag points to the same container image as `:1.4.0.5-pre12.  To get the _"latest"_ you need to run `docker pull ryshe/terraria:latest`.  I used the `:lastest` tag to make things easier for people not used to docker.  However the better practice is to _not_ use the `:lastest` tag and use the specific version tag.  So all  the instructions for running is the same, just switch `:latest` to `:1.4.0.5-pre12`.

**Comment by ryansheehan** [comment]
This is pretty stale at this point.  Please reopen if you have further questions.
