### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by viewfirst** [ryansheehan/terraria#57]
How should I modify the difficulty of the created world? There seems to be no corresponding setting in the config.json file?
Also, where can I find the authcode.txt file?

**Comment by ryansheehan** [comment]
First make sure to update the latest container image:

```
docker pull ryshe/terraria:latest
```

try running *without* the autocreate flag

```
docker run -it --rm -p 7777:7777 -v $HOME/terraria/world:/root/.local/share/Terraria/Worlds ryshe/terraria:latest
```

There should be prompts for how difficult of a world you want.

![image](https://user-images.githubusercontent.com/7987783/97091816-451ada00-1604-11eb-9ee1-251740dea248.png)

**Comment by viewfirst** [comment]
My world has been created, how can I reselect the difficulty?

**Comment by viewfirst** [comment]
I restarted the server. Where can I find the tshock folder?

**Comment by ryansheehan** [comment]
Are you asking where you find the world files inside the container, or on the host machine?

The hint is on the volume flag, -v.  It goes -v <host path>:<container path>.  Check the command I mentioned above.

**Comment by ryansheehan** [comment]
Not sure how to answer your question.  The tshock directory is inside the container at /tshock.

**Comment by viewfirst** [comment]
The question I asked is inaccurate. I'm sorry, I have found the folder.
There is another question I need to consult with you. How should I change the language of the server? For example, after using a certain command, the system's feedback language is English, and I want to change it to Chinese.

**Comment by ryansheehan** [comment]
You're getting outside my realm of knowledge.  All I produced was the
docker container for the TShock project.  You may want to ask the TShock
team here: https://github.com/Pryaxis/TShock/discussions

**Comment by viewfirst** [comment]
OK，thanks。sorry。
