### ISSUE TITLE
Stuck at 'Server found' message in Terraria 1.3.1

### ISSUE THREAD

**Issue by matracey** [ryansheehan/terraria#6]
I've been trying to get a server set up on my cloud-based host for the last couple of days but haven't had any luck. I've tried the Docker hub image, building from the Dockerfile and building from the dev/Dockerfile. I've tried in my cloud Docker host, and I've also tried on a local VM. Nothing has worked.

When I try to connect via IP in the game, I just sit at the 'Server Found' message forever - it doesn't seem to time out. 
![snip_20160523235836](https://cloud.githubusercontent.com/assets/1207505/15487084/4cf4f1c2-2142-11e6-9659-970969757e25.png)

I've set the server up using the `docker run -it --name=terraria --user=root -p 7777:7777 -p 7777:7777/udp -v /var/terraria/world:/world ryshe/terraria`. I added `--user=root` in an attempt to rule out any permissions issues and I added the `-p 7777:7777/udp` to make sure that it wasn't an issue with the server not being accessible through UDP. Inbound security rules isn't an issue as I've checked the port using nmap. 

The world seems to load okay and I get to the following console prompt after it's loaded:
![snip_20160523225749](https://cloud.githubusercontent.com/assets/1207505/15486204/e1dd0f56-213b-11e6-86db-27af7fd5164f.png).

The only thing I can think would be that it's an incomatibility between TShock Server 4.3.12 and Terraria Client 1.3.1. I'm all out of other ideas, so maybe someone can help?

**Comment by ryansheehan** [comment]
Looks like TShock hasn't dropped a build for version 1.3.1.  They are usually quite fast at getting new server builds out.  As soon as I see the update, then I'll make sure the docker container follows as soon as possible.

**Comment by ryansheehan** [comment]
Updated the dev branch with the latest successful build of TShock.  It is a dev build, so expect bugs, but it might be enough for people who are too eager to wait.

docker pull ryshe/terraria:dev

**Comment by ryansheehan** [comment]
New 1.3.1.1 server should work now
