### ISSUE TITLE
Cannot Run vanilla-1.4.2.3 (ARMv7)

### ISSUE THREAD

**Issue by ronelm2000** [ryansheehan/terraria#76]
Tried command as follows:
![image](https://user-images.githubusercontent.com/12634987/118745965-e4960780-b889-11eb-9425-9d47f0746ef6.png)

Full commands used are as follows:
```sh
pi@raspberrypi:~ $ sudo docker run -it -p 7777:7777 --rm -v $HOME/terraria/world:/root/.local/share/Terraria/Worlds ryshe/terraria:latest

Bootstrap:
world_file_name=
configpath=/root/.local/share/Terraria/Worlds
logpath=/tshock/logs

Copying plugins...
cp: cannot stat '/plugins/*': No such file or directory
No world file specified in environment WORLD_FILENAME.
Running server setup...
Error Logging Enabled.
TerrariaAPI Version: 2.1.0.0 (Protocol v1.4.2.2 (237), OTAPI 1.4.2.2)
[TShock] Info Config path has been set to /root/.local/share/Terraria/Worlds
[TShock] Info Log path has been set to /tshock/logs
TShock was improperly shut down. Please use the exit command in the future to prevent this.
TShock 4.5.2.0 (April Lyrids edition) now running.
AutoSave Enabled
Backups Disabled
Welcome to TShock for Terraria!
TShock comes with no warranty & is free software.
You can modify & distribute it under the terms of the GNU GPLv3.
[Server API] Info Plugin TShock v4.5.2.0 (by The TShock Team) initiated.
Terraria Server v1.4.2.2

n		New World
d <number>	Delete World

Choose World: pi@raspberrypi:~ $ 
pi@raspberrypi:~ $ sudo docker run -it -p 7777:7777 --rm -v $HOME/terraria/world:/root/.local/share/Terraria/Worlds ryshe/terraria:vanilla-1.4.2.3
Unable to find image 'ryshe/terraria:vanilla-1.4.2.3' locally
vanilla-1.4.2.3: Pulling from ryshe/terraria
cd38ad753522: Already exists 
678b77b1123e: Already exists 
35ee2966b2ed: Already exists 
eeb30a8d972e: Pull complete 
Digest: sha256:06f0d64d9ebe6c8fa74d9dbb91290ccc5bde4ea05c14bc056e3a9736d19c6494
Status: Downloaded newer image for ryshe/terraria:vanilla-1.4.2.3
/lib64/ld-linux-x86-64.so.2: No such file or directory
```

**Comment by ryansheehan** [comment]
I wonder if this has to do with it trying to link a x86-64 binary on the
pi, isn't the pi arm-based?

**Comment by ronelm2000** [comment]
> 
> I wonder if this has to do with it trying to link a x86-64 binary on the pi, isn't the pi arm-based?
Correct, that's why it's weird.
And yes, I'm using Raspberry Pi 4 Model B to run this, so this should be using ARMv7 digest.

**Comment by ryansheehan** [comment]
try

docker pull ryshe/terraria@
sha256:2bd100d233c8dba2888ed3304ad5bdacd677f21e3fa06665196273901ff12b80

I've never really tried to pull by digest, but hopefully that works.

**Comment by ronelm2000** [comment]
![image](https://user-images.githubusercontent.com/12634987/118771027-98ac8800-b8b4-11eb-9b31-2e190fef03af.png)
Unfortunately it still does the same thing; I still don't get why does the ARMv7 digest pulls out x86 resources.

**Comment by ryansheehan** [comment]
I wonder if a different version of mono might fix this issue on ARM.  Have you tried rebuilding the container against `mono:6.12.0.107`?

**Comment by ronelm2000** [comment]
Unforunately, it still didn't work. My theory is that you'd need to manually add missing ELF libaries from TerrariaServer (see https://blog.oddbit.com/post/2015-02-05-creating-minimal-docker-images/ for more details.)

I'll see what I can do, but for now, it'll require me to manually download and perform `ldd` from TerrariaServer, I think.

**Comment by ronelm2000** [comment]
Update: I got it working by directly using mono.

I'm not sure how to implement this on your dockerfiles, but this is the change I did (should make ARMv7 and ARMv8 working, at least)

```dockerfile
FROM alpine:3.11.6 AS base

RUN apk add --update-cache \
    unzip

ENV DL_LINK=https://terraria.org/system/dedicated_servers/archives/000/000/046/original/terraria-server-1423.zip
ENV DL_VERSION=1423
ENV DL_FILE=terraria-server-1423.zip

ADD $DL_LINK /$DL_FILE

RUN unzip /$DL_FILE -d /terraria && \
    mkdir /terraria-server && \
    mv /terraria/$DL_VERSION/Linux/* /terraria-server && \
    chmod +x /terraria-server/TerrariaServer && \
    chmod +x /terraria-server/TerrariaServer.bin.x86_64

FROM mono:6.8.0.96-slim
LABEL maintainer="Ryan Sheehan <rsheehan@gmail.com>"

EXPOSE 7777

VOLUME ["/root/.local/share/Terraria/Worlds", "/config"]

COPY --from=base /terraria-server/ /terraria-server/

ENTRYPOINT ["mono", "/terraria-server/TerrariaServer.exe"]
```

**Comment by ryansheehan** [comment]
I "tested" this change locally seems to work fine on linux.  I pushed a new
tag vanilla-1.4.2.3-2.  Would you be willing to verify it works for you?
Also thanks for the contribution.

**Comment by jgiacomo** [comment]
I think I've run into a similar issue trying to run the mobile server. I'm using Portainer on a Raspberry Pi 3 and launched with a simple docker-compose.yml file pulling the mobile-latest tag. However, the server doesn't start and in the logs I see the following: 

`a-server/TerrariaServer: line 42: ./TerrariaServer.bin.x86: cannot execute binary file: Exec format error`

It appears it is also trying to run an x86 binary on this arm32 system. I'm very new to Docker and don't understand most of what is in the posts above, but was hoping this would be a similar fix for the mobile server build.

**Comment by ryansheehan** [comment]
@jgiacomo, I switched the mobile version to full mono, and removed the
references to the packaged mono files.  The mobile version seems to be
loading better now, at least when the server is created on linux.  Please
try rerunning with the tag mobile-1.4.0.5-2

**Comment by jgiacomo** [comment]
That did it! Thank you so much @ryansheehan for your time and effort. I've never played Terraria, but my kids are super excited that this works. I was able to clone your repository and modify the Dockerfile and learned how to build the docker image, but still could not get it to run (I believe because of the dll file issues in mono that @ronelm2000 mentioned above). So glad you fixed it.

**Comment by ronelm2000** [comment]
ARMv7 also works with the new tag/digest. I can't test locally for ARMv8 (because I don't have it), but it should also work there.
