### ISSUE TITLE
Error after creation

### ISSUE THREAD

**Issue by kKen94** [ryansheehan/terraria#96]
![image](https://user-images.githubusercontent.com/46461611/148663816-08f5002a-a741-4b4b-8eee-843387500905.png)

Hi,

this is my docker-compose.

And this is the error after initialization:

![image](https://user-images.githubusercontent.com/46461611/148663843-4de6a8db-7dfb-4a0a-b234-d2e2ce02a7b8.png)

**Comment by ryansheehan** [comment]
is this with a new file or were you trying to create a new world?

**Comment by kKen94** [comment]
I'm trying to create new world

**Comment by nerdynigel** [comment]
The server runs fine on 1st creation. When exiting it appears to corrupt the saved world which is unable to be run again. 
![image](https://user-images.githubusercontent.com/2536333/149607225-a5c874f4-1d64-4a25-bdc2-c81888d35f88.png)

**Comment by Dorque** [comment]
Can you try adding the following to your docker compose? Something to do with tshock not running properly without stdin (related to https://github.com/ryansheehan/terraria/issues/14)
`stdin_open: true #docker run -i
tty: true #docker run -t`

**Comment by nerdynigel** [comment]
that did the trick. Thanks

**Comment by kKen94** [comment]
> Can you try adding the following to your docker compose? Might be something to do with tshock not running properly without stdin (related to #14)
> 
> stdin_open: true #docker run -i tty: true #docker run -t

Works!
