### ISSUE TITLE
How to change game mode?

### ISSUE THREAD

**Issue by SatoriNya** [ryansheehan/terraria#98]
How to change the difficulty and the world mode(not world scale) when i run the docker container? what parameter should i input?

**Comment by ryansheehan** [comment]
I think it's in my readme, but

sudo docker run -it -p 7777:7777 --rm -v
$HOME/terraria/world:/root/.local/share/Terraria/Worlds
ryshe/terraria:latest

Should do what you're looking for.  Just remember that the directory
$HOME/terraria/world
Needs to exist on the host machine to save your world file.

**Comment by SatoriNya** [comment]
well... readme just say how to set world scale(small,large,)... and I want to generate a master difficulty

**Comment by SatoriNya** [comment]
oh i got it Thank you
